export enum ActionType {
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    ADD_FROM_CART = 'ADD_FROM_CART',
    CLEAR_CART_ITEM = 'CLEAR_CART_ITEM',
    CLEAR_ITEM = 'CLEAR_ITEM'
}
